//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalVirtualComputer {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class loc_english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal loc_english() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationalVirtualComputer.loc_english", typeof(loc_english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ... Assign과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANI_ASSIGN_SOMETING {
            get {
                return ResourceManager.GetString("ANI_ASSIGN_SOMETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrease과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANI_DECREASE_SOMETING {
            get {
                return ResourceManager.GetString("ANI_DECREASE_SOMETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANI_INCREASE_SOMETING {
            get {
                return ResourceManager.GetString("ANI_INCREASE_SOMETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Value of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANI_OF_VALUE {
            get {
                return ResourceManager.GetString("ANI_OF_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COLOR_BLUE {
            get {
                return ResourceManager.GetString("COLOR_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COLOR_GREEN {
            get {
                return ResourceManager.GetString("COLOR_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COLOR_RED {
            get {
                return ResourceManager.GetString("COLOR_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_ADD {
            get {
                return ResourceManager.GetString("COMMAND_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mov과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_ASSIGN {
            get {
                return ResourceManager.GetString("COMMAND_ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_CLEAR {
            get {
                return ResourceManager.GetString("COMMAND_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_DELAY {
            get {
                return ResourceManager.GetString("COMMAND_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loopend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_LOOPEND {
            get {
                return ResourceManager.GetString("COMMAND_LOOPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loopstart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_LOOPSTART {
            get {
                return ResourceManager.GetString("COMMAND_LOOPSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   putpixel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_PUTPIXEL {
            get {
                return ResourceManager.GetString("COMMAND_PUTPIXEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sub과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND_SUB {
            get {
                return ResourceManager.GetString("COMMAND_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Float1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FLOAT1 {
            get {
                return ResourceManager.GetString("FLOAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Float2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FLOAT2 {
            get {
                return ResourceManager.GetString("FLOAT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Int1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INT1 {
            get {
                return ResourceManager.GetString("INT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Int2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INT2 {
            get {
                return ResourceManager.GetString("INT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOOP {
            get {
                return ResourceManager.GetString("LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STRING1 {
            get {
                return ResourceManager.GetString("STRING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STRING2 {
            get {
                return ResourceManager.GetString("STRING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_CODE {
            get {
                return ResourceManager.GetString("UI_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code Animation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_CODE_ANIMATION {
            get {
                return ResourceManager.GetString("UI_CODE_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Palatte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_COLOR_PALATTE {
            get {
                return ResourceManager.GetString("UI_COLOR_PALATTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_CPU_INFO {
            get {
                return ResourceManager.GetString("UI_CPU_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_EXECUTE {
            get {
                return ResourceManager.GetString("UI_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inst Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_INSTRUCTION_NUMBER {
            get {
                return ResourceManager.GetString("UI_INSTRUCTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_MEMORY_INFO {
            get {
                return ResourceManager.GetString("UI_MEMORY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_MONITOR {
            get {
                return ResourceManager.GetString("UI_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_SPEED {
            get {
                return ResourceManager.GetString("UI_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_TIME {
            get {
                return ResourceManager.GetString("UI_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_VARIABLE_NAME {
            get {
                return ResourceManager.GetString("UI_VARIABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_VARIABLE_TYPE {
            get {
                return ResourceManager.GetString("UI_VARIABLE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UI_VARIABLE_VALUE {
            get {
                return ResourceManager.GetString("UI_VARIABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- Can&apos;t assign this to same variable.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING_CANT_ASSIGN_TO_SAME_VARIABLE {
            get {
                return ResourceManager.GetString("WARNING_CANT_ASSIGN_TO_SAME_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- Can&apos;t convert it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING_CANT_CONVERT {
            get {
                return ResourceManager.GetString("WARNING_CANT_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t use variable value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING_CANT_USE_VARIABLE_VALUE {
            get {
                return ResourceManager.GetString("WARNING_CANT_USE_VARIABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- Doesn&apos;t exist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING_DOESNT_EXIST {
            get {
                return ResourceManager.GetString("WARNING_DOESNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- Doesn&apos;t exist this command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING_DOESNT_EXIST_COMMAND {
            get {
                return ResourceManager.GetString("WARNING_DOESNT_EXIST_COMMAND", resourceCulture);
            }
        }
    }
}
