//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalVirtualComputer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationalVirtualComputer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   을 할당과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ANI_ASSIGN_SOMETING {
            get {
                return ResourceManager.GetString("ANI_ASSIGN_SOMETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   을 감소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ANI_DECREASE_SOMETING {
            get {
                return ResourceManager.GetString("ANI_DECREASE_SOMETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   을 증가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ANI_INCREASE_SOMETING {
            get {
                return ResourceManager.GetString("ANI_INCREASE_SOMETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의 값과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ANI_OF_VALUE {
            get {
                return ResourceManager.GetString("ANI_OF_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파랑과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COLOR_BLUE {
            get {
                return ResourceManager.GetString("COLOR_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COLOR_GREEN {
            get {
                return ResourceManager.GetString("COLOR_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빨강과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COLOR_RED {
            get {
                return ResourceManager.GetString("COLOR_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   더하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_ADD {
            get {
                return ResourceManager.GetString("COMMAND_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   할당과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_ASSIGN {
            get {
                return ResourceManager.GetString("COMMAND_ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_CLEAR {
            get {
                return ResourceManager.GetString("COMMAND_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지연과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_DELAY {
            get {
                return ResourceManager.GetString("COMMAND_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복끝과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_LOOPEND {
            get {
                return ResourceManager.GetString("COMMAND_LOOPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_LOOPSTART {
            get {
                return ResourceManager.GetString("COMMAND_LOOPSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   점찍기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_PUTPIXEL {
            get {
                return ResourceManager.GetString("COMMAND_PUTPIXEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빼기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMMAND_SUB {
            get {
                return ResourceManager.GetString("COMMAND_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실수1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FLOAT1 {
            get {
                return ResourceManager.GetString("FLOAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실수2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FLOAT2 {
            get {
                return ResourceManager.GetString("FLOAT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정수1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string INT1 {
            get {
                return ResourceManager.GetString("INT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정수2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string INT2 {
            get {
                return ResourceManager.GetString("INT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOOP {
            get {
                return ResourceManager.GetString("LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING1 {
            get {
                return ResourceManager.GetString("STRING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문자열2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STRING2 {
            get {
                return ResourceManager.GetString("STRING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_CODE {
            get {
                return ResourceManager.GetString("UI_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   코드 애니메이션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_CODE_ANIMATION {
            get {
                return ResourceManager.GetString("UI_CODE_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색상 팔레트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_COLOR_PALATTE {
            get {
                return ResourceManager.GetString("UI_COLOR_PALATTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_CPU_INFO {
            get {
                return ResourceManager.GetString("UI_CPU_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_EXECUTE {
            get {
                return ResourceManager.GetString("UI_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   명령어 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_INSTRUCTION_NUMBER {
            get {
                return ResourceManager.GetString("UI_INSTRUCTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메모리 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_MEMORY_INFO {
            get {
                return ResourceManager.GetString("UI_MEMORY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_MONITOR {
            get {
                return ResourceManager.GetString("UI_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_SPEED {
            get {
                return ResourceManager.GetString("UI_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_TIME {
            get {
                return ResourceManager.GetString("UI_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변수이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_VARIABLE_NAME {
            get {
                return ResourceManager.GetString("UI_VARIABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_VARIABLE_TYPE {
            get {
                return ResourceManager.GetString("UI_VARIABLE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   값과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_VARIABLE_VALUE {
            get {
                return ResourceManager.GetString("UI_VARIABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- 이 값을 동일한 변수에 대입할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WARNING_CANT_ASSIGN_TO_SAME_VARIABLE {
            get {
                return ResourceManager.GetString("WARNING_CANT_ASSIGN_TO_SAME_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- 를 변환할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WARNING_CANT_CONVERT {
            get {
                return ResourceManager.GetString("WARNING_CANT_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변수값을 사용할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WARNING_CANT_USE_VARIABLE_VALUE {
            get {
                return ResourceManager.GetString("WARNING_CANT_USE_VARIABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WARNING_DOESNT_EXIST {
            get {
                return ResourceManager.GetString("WARNING_DOESNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- 명령어가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WARNING_DOESNT_EXIST_COMMAND {
            get {
                return ResourceManager.GetString("WARNING_DOESNT_EXIST_COMMAND", resourceCulture);
            }
        }
    }
}
